# Use the PHP 7.3 runtime by replacing "php72" below with "php73"
runtime: php73

handlers:
- url: /css
  static_dir: css
- url: /media
  static_dir: media
- url: /js
  static_dir: js


# Defaults to "serve index.php" 
# entrypoint: serve base.php

# If your main page is index.php, comment the above entrypoint setting 