# Use the PHP 7.3 runtime by replacing "php72" below with ""
# Defaults to "serve index.php" 
# entrypoint: serve base.php

# If your main page is index.php, comment the above entrypoint setting 



runtime: python27 #php73 #
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/angular/index.html
  upload: dist/angular/index.html

- url: /
  static_dir: dist/angular

- url: /css
  static_dir: css
- url: /media
  static_dir: media
- url: /upload
  static_dir: upload
- url: /js
  static_dir: js